CREATE TABLE customer (
    id    bigint GENERATED BY DEFAULT AS IDENTITY,
    name varchar(255) NOT NULL,
    street varchar(255) DEFAULT NULL, 
    city varchar(255) DEFAULT NULL, 
    county varchar(100) DEFAULT NULL, 
    postcode varchar(10) DEFAULT NULL,
    PRIMARY KEY (id)
);
CREATE TABLE product (
    id    bigint GENERATED BY DEFAULT AS IDENTITY,
    price decimal(19, 2) NOT NULL,
    sku   varchar(255),
    description varchar(255) NOT NULL,
    PRIMARY KEY (id)
);
ALTER TABLE product
    ADD CONSTRAINT UK_q1mafxn973ldq80m1irp3mpvq UNIQUE (sku);
